spring:
    cloud:
        gateway:
            routes:
                - id: guides
                  predicates: 
                    - Path=/guides
                    - After=2020-10-11T01:01:01:123-45:67[US/Central]
                  uri: https://spring.io
