spring:
    cloud:
        gateway:
            routes:
                - id: guides
                  predicates: 
                    - Path=/guides
                  filters:
                    - name: SCGWPreFilter
                  uri: https://spring.io
