spring:
    cloud:
        gateway:
            routes:
                - id: guides
                  predicates: 
                    - Path=/guides
                  filters:
                    - name: SCGWPreFilter
                  uri: https://spring.io
                - id: resource
                  uri: http://resource:9000
                  predicates:
                    - Path=/queueit
                  filters:
                    - TokenRelay=
                    - RemoveRequestHeader=Cookie